name: morning
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID1: ${{ secrets.TEMPLATE_ID1 }}
      TEMPLATE_ID_aq: ${{ secrets.TEMPLATE_ID_aq }}
      TEMPLATE_ID_pl: ${{ secrets.TEMPLATE_ID_pl }}
      TEMPLATE_ID_jq: ${{ secrets.TEMPLATE_ID_jq }}
      USER_ID1: ${{ secrets.USER_ID1 }}
      USER_ID2: ${{ secrets.USER_ID2 }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}
      PROVINCE: ${{ secrets.PROVINCE }}
      LAST_JQ: ${{ secrets.LAST_JQ }}
      END_JQ: ${{ secrets.END_JQ }}
      NEXT_JQ: ${{ secrets.NEXT_JQ }}
